### ISSUE TITLE
onTap method to be able to show the image in light box

### ISSUE THREAD

**Issue by otusweb** [kkemple/react-native-sideswipe#28]
Feature request, i want to be able to tap on an image to open it in a light box. All I really need is a onTap method that I can provide.

**Comment by kkemple** [comment]
Hey @otusweb, thanks for submitting this issue! I'm curious why an onPress handler on a TouchableOpacity on children is not enough? Are you getting issues with onPress not working?

**Comment by otusweb** [comment]
I’m still new at react native. So I’m not sure I fully understand your proposed solution. Do you happen to have an exemple handy?

**Comment by msevestre** [comment]
@otusweb You are responsible to render each item displayed by the sideswipe component. What Kurtis suggests (I believe),  is to simply wrap each rendered item in a `TouchableOpacity`. You can then add an onPress handler that could in your case open the underlying image in a light box. 

Does this make sense?

**Comment by otusweb** [comment]
@msevestre You're right. I ended up doing just that. Thanks

**Comment by kkemple** [comment]
@msevestre thanks for getting to this question! sorry I didn't respond faster @otusweb!
