### ISSUE TITLE
carousel locks when used in flatlist

### ISSUE THREAD

**Issue by d12544** [kkemple/react-native-sideswipe#42]
Please make sure these boxes are checked before submitting your issue!

- [x] I ran `[envinfo](https://www.npmjs.com/package/envinfo)` and added results to issue (if bug related)
- [x] I created a reproduction example in [expo](https://snack.expo.io) (if bug related)

**Comment by kkemple** [comment]
high, you didn't do either of the requested things for opening a bug, i'm going to close this until the details of the issue are added
